# Generated by Django 6.0.7 on 2026-08-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nba_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
