# Generated by Django 6.0.7 on 2026-08-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_nba_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='nba_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
